name: Trellis Deploy
description: Deploy Trellis, Bedrock and Sage (optionally) via GitHub Actions

branding:
  icon: upload-cloud
  color: blue

inputs:
  role_file:
    description: galaxy role file containing a list of roles to be imported
    default: galaxy.yml
    required: false

  vault_password:
    description: ansible vault password
    required: false

  vault_password_file:
    description: ansible vault password file to use. Must be the same one in ansible.cfg (if applicable)
    default: .vault_pass
    required: false

  site_env:
    description: the environment to deploy to (staging, production, etc)
    required: true

  site_name:
    description: the WordPress site to deploy (name defined in wordpress_sites)
    required: false

  site_key:
    description: Search the WordPress site by key == value
    required: false

  site_value:
    description: Search the WordPress site by key == value
    required: false

  site_path:
    description: Path where site lives
    default: ${{ github.workspace }}
    required: false

  trellis_path:
    description: Path where trellis lives
    default: ${{ github.workspace }}/trellis
    required: false

  group_vars:
    description: Group vars where sites are defined.
    default: false
    required: false

  verbose:
    description: Whether to provide verbose output
    required: false

  ansible_strategy:
    description: Ansible strategy to use, supports mitogen.
    default: linear
    required: false

  yarn_cache:
    description: Yarn cache path, used for caching the cache.
    default: ${{ github.workspace }}/.cache/yarn
    required: false

  node_version:
    description: Node version to use (e.g. 18, 20, 22)
    default: "20"
    required: false

runs:
  using: composite
  steps:
    - run: |
        docker run \
          -e ANSIBLE_HOST_KEY_CHECKING=false \
          -e ANSIBLE_STRATEGY=${{ inputs.ansible_strategy }} \
          -e YARN_CACHE_FOLDER=${{ inputs.yarn_cache }} \
          ghcr.io/tgeorgel/trellis-action:v1.4.1-node${{ inputs.node_version }}
      shell: bash